<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UploadsHits', 'doctrine');

/**
 * BaseUploadsHits
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $upid
 * @property integer $uid
 * @property Users $Users
 * @property Uploads $Uploads
 * 
 * @method integer     getUpid()    Returns the current record's "upid" value
 * @method integer     getUid()     Returns the current record's "uid" value
 * @method Users       getUsers()   Returns the current record's "Users" value
 * @method Uploads     getUploads() Returns the current record's "Uploads" value
 * @method UploadsHits setUpid()    Sets the current record's "upid" value
 * @method UploadsHits setUid()     Sets the current record's "uid" value
 * @method UploadsHits setUsers()   Sets the current record's "Users" value
 * @method UploadsHits setUploads() Sets the current record's "Uploads" value
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUploadsHits extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('uploads_hits');
        $this->hasColumn('upid', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('uid', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users', array(
             'local' => 'uid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Uploads', array(
             'local' => 'upid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}