<?php

/**
 * BaseShoutboxComs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Shoutbox $Shoutbox
 * 
 * @method Shoutbox     getShoutbox() Returns the current record's "Shoutbox" value
 * @method ShoutboxComs setShoutbox() Sets the current record's "Shoutbox" value
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShoutboxComs extends MsgMessages
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Shoutbox', array(
             'local' => 'shtid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}