<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MsgVotes', 'doctrine');

/**
 * BaseMsgVotes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $uid
 * @property integer $mid
 * @property boolean $vote
 * @property Users $Users
 * @property MsgMessages $MsgMessages
 * 
 * @method integer     getUid()         Returns the current record's "uid" value
 * @method integer     getMid()         Returns the current record's "mid" value
 * @method boolean     getVote()        Returns the current record's "vote" value
 * @method Users       getUsers()       Returns the current record's "Users" value
 * @method MsgMessages getMsgMessages() Returns the current record's "MsgMessages" value
 * @method MsgVotes    setUid()         Sets the current record's "uid" value
 * @method MsgVotes    setMid()         Sets the current record's "mid" value
 * @method MsgVotes    setVote()        Sets the current record's "vote" value
 * @method MsgVotes    setUsers()       Sets the current record's "Users" value
 * @method MsgVotes    setMsgMessages() Sets the current record's "MsgMessages" value
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMsgVotes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('msg_votes');
        $this->hasColumn('uid', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('mid', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('vote', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users', array(
             'local' => 'uid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('MsgMessages', array(
             'local' => 'mid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}