<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FrmCats', 'doctrine');

/**
 * BaseFrmCats
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $FrmForums
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getFrmForums() Returns the current record's "FrmForums" collection
 * @method FrmCats             setName()      Sets the current record's "name" value
 * @method FrmCats             setFrmForums() Sets the current record's "FrmForums" collection
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFrmCats extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('frm_cats');
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FrmForums', array(
             'local' => 'id',
             'foreign' => 'cat'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}