<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PollVotes', 'doctrine');

/**
 * BasePollVotes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $choice
 * @property integer $uid
 * @property PollChoices $PollChoices
 * @property Users $Users
 * 
 * @method integer     getChoice()      Returns the current record's "choice" value
 * @method integer     getUid()         Returns the current record's "uid" value
 * @method PollChoices getPollChoices() Returns the current record's "PollChoices" value
 * @method Users       getUsers()       Returns the current record's "Users" value
 * @method PollVotes   setChoice()      Sets the current record's "choice" value
 * @method PollVotes   setUid()         Sets the current record's "uid" value
 * @method PollVotes   setPollChoices() Sets the current record's "PollChoices" value
 * @method PollVotes   setUsers()       Sets the current record's "Users" value
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePollVotes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poll_votes');
        $this->hasColumn('choice', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('uid', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PollChoices', array(
             'local' => 'choice',
             'foreign' => 'id'));

        $this->hasOne('Users', array(
             'local' => 'uid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}