<?php

/**
 * BasePmMessages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property PmTopics $PmTopics
 * 
 * @method PmTopics   getPmTopics() Returns the current record's "PmTopics" value
 * @method PmMessages setPmTopics() Sets the current record's "PmTopics" value
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePmMessages extends MsgMessages
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PmTopics', array(
             'local' => 'pmid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}