<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PollChoices', 'doctrine');

/**
 * BasePollChoices
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $poll
 * @property string $choice
 * @property Polls $Polls
 * @property Doctrine_Collection $PollVotes
 * 
 * @method integer             getPoll()      Returns the current record's "poll" value
 * @method string              getChoice()    Returns the current record's "choice" value
 * @method Polls               getPolls()     Returns the current record's "Polls" value
 * @method Doctrine_Collection getPollVotes() Returns the current record's "PollVotes" collection
 * @method PollChoices         setPoll()      Sets the current record's "poll" value
 * @method PollChoices         setChoice()    Sets the current record's "choice" value
 * @method PollChoices         setPolls()     Sets the current record's "Polls" value
 * @method PollChoices         setPollVotes() Sets the current record's "PollVotes" collection
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePollChoices extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poll_choices');
        $this->hasColumn('poll', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('choice', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Polls', array(
             'local' => 'poll',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('PollVotes', array(
             'local' => 'id',
             'foreign' => 'choice'));
    }
}