<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PmTopics', 'doctrine');

/**
 * BasePmTopics
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $PmParticipants
 * @property Doctrine_Collection $PmMessages
 * 
 * @method string              getTitle()          Returns the current record's "title" value
 * @method Doctrine_Collection getPmParticipants() Returns the current record's "PmParticipants" collection
 * @method Doctrine_Collection getPmMessages()     Returns the current record's "PmMessages" collection
 * @method PmTopics            setTitle()          Sets the current record's "title" value
 * @method PmTopics            setPmParticipants() Sets the current record's "PmParticipants" collection
 * @method PmTopics            setPmMessages()     Sets the current record's "PmMessages" collection
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePmTopics extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pm_topics');
        $this->hasColumn('title', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PmParticipants', array(
             'local' => 'id',
             'foreign' => 'mpid'));

        $this->hasMany('PmMessages', array(
             'local' => 'id',
             'foreign' => 'pmid'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}