<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ips', 'doctrine');

/**
 * BaseIps
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ip
 * @property integer $uid
 * @property Users $Users
 * 
 * @method string  getIp()    Returns the current record's "ip" value
 * @method integer getUid()   Returns the current record's "uid" value
 * @method Users   getUsers() Returns the current record's "Users" value
 * @method Ips     setIp()    Sets the current record's "ip" value
 * @method Ips     setUid()   Sets the current record's "uid" value
 * @method Ips     setUsers() Sets the current record's "Users" value
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIps extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ips');
        $this->hasColumn('ip', 'string', 45, array(
             'type' => 'string',
             'primary' => true,
             'length' => 45,
             ));
        $this->hasColumn('uid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users', array(
             'local' => 'uid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}