<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PmParticipants', 'doctrine');

/**
 * BasePmParticipants
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mpid
 * @property integer $mpmid
 * @property boolean $readed
 * @property boolean $deleted
 * @property Users $Users
 * @property PmTopics $PmTopics
 * 
 * @method integer        getMpid()     Returns the current record's "mpid" value
 * @method integer        getMpmid()    Returns the current record's "mpmid" value
 * @method boolean        getReaded()   Returns the current record's "readed" value
 * @method boolean        getDeleted()  Returns the current record's "deleted" value
 * @method Users          getUsers()    Returns the current record's "Users" value
 * @method PmTopics       getPmTopics() Returns the current record's "PmTopics" value
 * @method PmParticipants setMpid()     Sets the current record's "mpid" value
 * @method PmParticipants setMpmid()    Sets the current record's "mpmid" value
 * @method PmParticipants setReaded()   Sets the current record's "readed" value
 * @method PmParticipants setDeleted()  Sets the current record's "deleted" value
 * @method PmParticipants setUsers()    Sets the current record's "Users" value
 * @method PmParticipants setPmTopics() Sets the current record's "PmTopics" value
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePmParticipants extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pm_participants');
        $this->hasColumn('mpid', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('mpmid', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('readed', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('deleted', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users', array(
             'local' => 'mpmid',
             'foreign' => 'id'));

        $this->hasOne('PmTopics', array(
             'local' => 'mpid',
             'foreign' => 'id'));
    }
}