<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Categories', 'doctrine');

/**
 * BaseCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $picture
 * @property Doctrine_Collection $Uploads
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method string              getPicture() Returns the current record's "picture" value
 * @method Doctrine_Collection getUploads() Returns the current record's "Uploads" collection
 * @method Categories          setName()    Sets the current record's "name" value
 * @method Categories          setPicture() Sets the current record's "picture" value
 * @method Categories          setUploads() Sets the current record's "Uploads" collection
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategories extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categories');
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('picture', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Uploads', array(
             'local' => 'id',
             'foreign' => 'cat'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($nestedset0);
        $this->actAs($sluggable0);
    }
}