<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FrmTopicsUsr', 'doctrine');

/**
 * BaseFrmTopicsUsr
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $topic
 * @property integer $uid
 * @property boolean $following
 * @property boolean $replied
 * @property integer $lastmsgid
 * @property Users $Users
 * @property FrmTopics $FrmTopics
 * @property MsgMessages $MsgMessages
 * 
 * @method integer      getTopic()       Returns the current record's "topic" value
 * @method integer      getUid()         Returns the current record's "uid" value
 * @method boolean      getFollowing()   Returns the current record's "following" value
 * @method boolean      getReplied()     Returns the current record's "replied" value
 * @method integer      getLastmsgid()   Returns the current record's "lastmsgid" value
 * @method Users        getUsers()       Returns the current record's "Users" value
 * @method FrmTopics    getFrmTopics()   Returns the current record's "FrmTopics" value
 * @method MsgMessages  getMsgMessages() Returns the current record's "MsgMessages" value
 * @method FrmTopicsUsr setTopic()       Sets the current record's "topic" value
 * @method FrmTopicsUsr setUid()         Sets the current record's "uid" value
 * @method FrmTopicsUsr setFollowing()   Sets the current record's "following" value
 * @method FrmTopicsUsr setReplied()     Sets the current record's "replied" value
 * @method FrmTopicsUsr setLastmsgid()   Sets the current record's "lastmsgid" value
 * @method FrmTopicsUsr setUsers()       Sets the current record's "Users" value
 * @method FrmTopicsUsr setFrmTopics()   Sets the current record's "FrmTopics" value
 * @method FrmTopicsUsr setMsgMessages() Sets the current record's "MsgMessages" value
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFrmTopicsUsr extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('frm_topicsusr');
        $this->hasColumn('topic', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('uid', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('following', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('replied', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('lastmsgid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users', array(
             'local' => 'uid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('FrmTopics', array(
             'local' => 'topic',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('MsgMessages', array(
             'local' => 'lastmsgid',
             'foreign' => 'id'));
    }
}