<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MsgMessages', 'doctrine');

/**
 * BaseMsgMessages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $author
 * @property string $content
 * @property string $module
 * @property integer $tid
 * @property integer $pmid
 * @property integer $shtid
 * @property integer $pollid
 * @property integer $upid
 * @property Users $Users
 * @property Doctrine_Collection $MsgVotes
 * @property Doctrine_Collection $FrmTopicsUsr
 * 
 * @method integer             getAuthor()       Returns the current record's "author" value
 * @method string              getContent()      Returns the current record's "content" value
 * @method string              getModule()       Returns the current record's "module" value
 * @method integer             getTid()          Returns the current record's "tid" value
 * @method integer             getPmid()         Returns the current record's "pmid" value
 * @method integer             getShtid()        Returns the current record's "shtid" value
 * @method integer             getPollid()       Returns the current record's "pollid" value
 * @method integer             getUpid()         Returns the current record's "upid" value
 * @method Users               getUsers()        Returns the current record's "Users" value
 * @method Doctrine_Collection getMsgVotes()     Returns the current record's "MsgVotes" collection
 * @method Doctrine_Collection getFrmTopicsUsr() Returns the current record's "FrmTopicsUsr" collection
 * @method MsgMessages         setAuthor()       Sets the current record's "author" value
 * @method MsgMessages         setContent()      Sets the current record's "content" value
 * @method MsgMessages         setModule()       Sets the current record's "module" value
 * @method MsgMessages         setTid()          Sets the current record's "tid" value
 * @method MsgMessages         setPmid()         Sets the current record's "pmid" value
 * @method MsgMessages         setShtid()        Sets the current record's "shtid" value
 * @method MsgMessages         setPollid()       Sets the current record's "pollid" value
 * @method MsgMessages         setUpid()         Sets the current record's "upid" value
 * @method MsgMessages         setUsers()        Sets the current record's "Users" value
 * @method MsgMessages         setMsgVotes()     Sets the current record's "MsgVotes" collection
 * @method MsgMessages         setFrmTopicsUsr() Sets the current record's "FrmTopicsUsr" collection
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMsgMessages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('msg_messages');
        $this->hasColumn('author', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('module', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('tid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pmid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('shtid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pollid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('upid', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->setSubClasses(array(
             'FrmMessages' => 
             array(
              'module' => 'forums',
             ),
             'PmMessages' => 
             array(
              'module' => 'pm',
             ),
             'ShoutboxComs' => 
             array(
              'module' => 'sht',
             ),
             'PollComs' => 
             array(
              'module' => 'poll',
             ),
             'NewsComs' => 
             array(
              'module' => 'news',
             ),
             'UploadsComs' => 
             array(
              'module' => 'up',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users', array(
             'local' => 'author',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('MsgVotes', array(
             'local' => 'id',
             'foreign' => 'mid'));

        $this->hasMany('FrmTopicsUsr', array(
             'local' => 'id',
             'foreign' => 'lastmsgid'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}