<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Donations', 'doctrine');

/**
 * BaseDonations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $donor
 * @property float $amount
 * @property Users $Users
 * 
 * @method integer   getDonor()  Returns the current record's "donor" value
 * @method float     getAmount() Returns the current record's "amount" value
 * @method Users     getUsers()  Returns the current record's "Users" value
 * @method Donations setDonor()  Sets the current record's "donor" value
 * @method Donations setAmount() Sets the current record's "amount" value
 * @method Donations setUsers()  Sets the current record's "Users" value
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDonations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('donations');
        $this->hasColumn('donor', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('amount', 'float', null, array(
             'type' => 'float',
             'unsigned' => true,
             'notnull' => true,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users', array(
             'local' => 'donor',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}