<?php

/**
 * CategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Categories');
    }
    
    public function getCats() {
      return Doctrine_Query::create()
    	->from('categories c')
      ->where("c.level = 0")
      ->groupBy("c.id")
      ->orderBy('name')
      ->useQueryCache(true)->setQueryCacheLifeSpan(3600*24)  
    	->execute();
    }
}