<?php

/**
 * DonationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DonationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DonationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Donations');
    }
    
    
    /**
     * Get amount concerning current month
     * @return type float
     */
    public function getAmount() {
      $q = Doctrine_Query::create()
              ->select("SUM(amount) AS value")
              ->from("Donations")
              ->where("created_at >= ?", date('Y-m-01'))
              ->useQueryCache(true)->setQueryCacheLifeSpan(3600*24)  
              ->useResultCache(true)->setResultCacheLifeSpan(60*60)
              ->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
      return ($q != null)?$q:0;
    }
    
    /**
     * Get best donors list
     * @param $l integer, number of results to return
     * @return type object array
     */
    public function getBestDonors($l = 10) {
      return Doctrine_Query::create()
            ->select("u.username, u.avatar, u.slug, SUM(d.amount) as value, d.donor")
            ->from("Donations d")
            ->leftJoin("d.Users u")
            ->groupBy("d.donor")
            ->orderBy("value desc")
            ->limit($l)
            ->execute();
    }
    
    /**
     * Get last transactions
     * @param $l integer, number of results to return
     * @return type object array
     */
    public function getLastDonations($l = 10) {
      return Doctrine_Query::create()
            ->from("Donations d")
            ->leftJoin("d.Users u")
            ->orderBy("created_at desc")
            ->limit($l)
            ->execute();
    }
}