<?php

/**
 * FrmCatsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrmCatsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FrmCatsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FrmCats');
    }
}