<?php

/**
 * FrmForumsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrmForumsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FrmForumsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FrmForums');
    }

    public function getForums() {
    	//$u = sfContext::getInstance()->getUser();
        $q = Doctrine_Query::create()
    		->select("c.*, f.*")
				->addSelect('(SELECT COUNT(t.id) FROM FrmTopics t WHERE t.forum = f.id) as cnt_topics')
    		->from("FrmCats c")
    		->leftJoin("c.FrmForums f")
            ->useQueryCache(true)->setQueryCacheLifeSpan(3600*24)  
            ->execute(array(), Doctrine::HYDRATE_ARRAY);
    	return $q;
    }
}