<?php

/**
 * FrmMessages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FrmMessages extends BaseFrmMessages
{
	public function getUpdatedAt() {
		return strtotime($this->_get("updated_at"));
	}

	public function getContent() {
		return strip_tags(
			$this->_get("content"), 
			'<p><a><span><br><img><div><b><strong><i><blockquote><pre><li><ul><ol><small><iframe>'
		);
	}

  public function save(Doctrine_Connection $con = null) {
    $q = parent::save();

    if (!$id) {
      Doctrine::getTable("Shoutbox")->setShout(
	      array("postedNewFrmReply", "comment_add.png", $this->FrmTopics->getTitle()), 
	      sfContext::getInstance()->getController()
	        ->genUrl("@topic?c=".$this->FrmTopics->FrmForums->FrmCats->getSlug().
	        	"&f=".$this->FrmTopics->FrmForums->getSlug().
	        	"&slug=".$this->FrmTopics->getSlug())
	    );
    }
	    
    return $q;
  }
}