<?php

/**
 * FrmTopicsUsrTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrmTopicsUsrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FrmTopicsUsrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FrmTopicsUsr');
    }
}