<?php

/**
 * FrmTopics
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FrmTopics extends BaseFrmTopics
{
	public function getUpdatedAt() {
		return strtotime($this->_get("updated_at"));
	}

  public function save(Doctrine_Connection $con = null) {
    $id = $this->getId();
    $q = parent::save();
    $f = Doctrine::getTable("FrmForums")->find($this->getForum());

    if (!$id) {
      Doctrine::getTable("Shoutbox")->setShout(
        array("postedNewTopic", "comment_add.png", $this->getTitle()), 
        sfContext::getInstance()->getController()
          ->genUrl("@topic?c=".$f->FrmCats->getSlug()."&f=".$f->getSlug()."&slug=".$this->getSlug())
      );
    }
    
    return $q;
  }
}
