<?php

/**
 * InvitesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvitesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvitesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Invites');
    }
}