<?php

/**
 * IpsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IpsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IpsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ips');
    }
}