<?php

/**
 * MsgMessages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MsgMessages extends BaseMsgMessages
{
	public function getUpdatedAt() {
		return strtotime($this->_get("updated_at"));
	}

	public function getContent() {
		return strip_tags(
			$this->_get("content"), 
			'<p><a><strike><span><br><img><div><b><strong><i><blockquote><pre><li><ul><ol>'
		);
		return $this->_get("content");
	}
}
