<?php

/**
 * MsgVotes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MsgVotes extends BaseMsgVotes
{
  public function replace(Doctrine_Connection $con = null) {
    // Saving vote
    $q = parent::replace();

    // Specify context
    if ($this->getVote() == 1) {
      $msg = "agreed your message.";
      $img = "thumb_up";
    }
    else {
      $msg = "disagreed your message.";
      $img = "thumb_down";
    }


    // Notify author
    Doctrine::getTable('Notifications')->setNotification(
      $msg,
      $img.".png",
      $this->MsgMessages->getContent(),
      "@homepage"
    )
    ->setOwner($this->MsgMessages->getAuthor())
    ->save();
	    
    return $q;
  }
}
