<?php

/**
 * MsgVotesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MsgVotesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MsgVotesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MsgVotes');
    }
}