<?php

/**
 * NewsComsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsComsTable extends MsgMessagesTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsComsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NewsComs');
    }
}