<?php

/**
 * News
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class News extends BaseNews
{
  public function save(Doctrine_Connection $con = null) {
    $id = $this->getId();
    $q = parent::save();

    if (!$id) {
      Doctrine::getTable("Shoutbox")->setShout(
	      array("postedNewNews", "newspaper_add.png", $this->getTitle()), 
	      sfContext::getInstance()->getController()
	        ->genUrl("@news?slug=".$this->getSlug())
	    );
    }
	    
    return $q;
  }
}
