<?php

/**
 * NotificationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotificationsTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object NotificationsTable
	 */
	public static function getInstance()
	{
	    return Doctrine_Core::getTable('Notifications');
	}
  
  public function getNotifications() {
  	return Doctrine_Query::create()
      ->select('n.*, u.username, u.avatar')
      ->from('Notifications n')
        ->leftJoin('n.Users u')
      ->where("owner = ?", sfContext::getInstance()->getUser()->getAttribute("id"))
      ->orderBy("id")
      ->limit(5)
      ->useQueryCache(true)->setQueryCacheLifeSpan(3600*24);
  }


  public function setNotification($msg, $picture, $extract=null, $link=null) {
  	$n = new Notifications();
  	$n->setUid(sfContext::getInstance()->getUser()->getAttribute("id"));
  	$n->setReaded(0);
  	$n->setPicture($picture);
  	$n->setMessage(sfContext::getInstance()->getI18N()->__($msg));
  	$n->setLink(sfContext::getInstance()->getController()->genUrl($link));

    // Limiting extract length
    if (strlen($extract) > 150)
      $extract = substr($extract, 0, 150).'...';
  	$n->setExtract($extract);

    // Returning Notifications object without saving if we've something to override
  	return $n;
  }
}