<?php

/**
 * Notifications
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Notifications extends BaseNotifications
{
  public function save(Doctrine_Connection $con = null) {
    // Saving notification only when user doesn't notify himself
    if ($this->getUid() != $this->getOwner())
      $q = parent::save();
	
    return $q;
  }
}
