<?php

/**
 * NotificationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotificationsTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object NotificationsTable
	 */
	public static function getInstance()
	{
	    return Doctrine_Core::getTable('Notifications');
	}
  
  public function getNotifications($u) {
  	return Doctrine_Query::create()
      ->select('n.*, u.username, u.avatar')
      ->from('Notifications n')
        ->leftJoin('n.Users u')
      ->where("owner = ?", $u)
      ->orderBy("id", "desc")
      ->limit(5)
      ->useQueryCache(true)->setQueryCacheLifeSpan(3600*24)  
      ->execute(array(), Doctrine::HYDRATE_ARRAY);
  }

  public function setNotification($msg, $extract=null) {
  	$n = new Notifications();
  	$n->setOwner(1);
  	$n->setUid(1);
  	$n->setReaded(0);
  	$n->setPicture("comment.png");
  	$n->setMessage($msg);
  	$n->setLink("#");
  	$n->setExtract($extract);
  	$n->save();
  	return $n;
  }
}