<?php

/**
 * PmMessagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PmMessagesTable extends MsgMessagesTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PmMessagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PmMessages');
    }
}