<?php

/**
 * PmParticipantsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PmParticipantsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PmParticipantsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PmParticipants');
    }
}