<?php

/**
 * PmTopicsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PmTopicsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PmTopicsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PmTopics');
    }

  public function getMessages($uid) {
  	return Doctrine_Query::create()
  	  ->select('t.*, m.*, u.slug, u.username, u.avatar, p.*')
      ->from('PmTopics t')
      ->leftJoin('t.PmMessages m')
        ->leftJoin('m.Users u')
  	  ->leftJoin('t.PmParticipants p')
  	  ->where('mpmid = ?', $uid)
      ->andWhere('deleted = 0')
      ->andWhere('m.created_at = t.updated_at') // Only the last post
      ->orderBy('t.updated_at DESC');
  }
}