<?php

/**
 * PollsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PollsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PollsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Polls');
    }
}