<?php

/**
 * PollChoicesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PollChoicesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PollChoicesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PollChoices');
    }
}