<?php

/**
 * PollVotesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PollVotesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PollVotesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PollVotes');
    }
}