<?php

/**
 * ShoutboxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShoutboxTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShoutboxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Shoutbox');
    }

  public function setShout($desc, $link=null) {
  	$s = new Shoutbox();
  	$s->setAuthor(sfContext::getInstance()->getUser()->getAttribute("id"));
  	if (is_array($desc)) {
  	  $s->setSystem(1);
  	  $s->setDescription(json_encode($desc));
  	  $s->setLink($link);
  	}
  	else {
  	  $s->setSystem(0);
  	  $s->setDescription($desc);
  	}
  	$s->save();
  	return $s;
  }

  public function getShouts($offsetId) {
  	return Doctrine_Query::create()
  	  ->select("s.*, u.username, u.avatar, u.slug")
  	  ->from("Shoutbox s")
  	  ->leftJoin('s.Users u')
  	  ->where("s.id > ?", $offsetId)
      ->andWhere("s.created_at > ?", date("Y-m-d", time()-3600*24*3))
      ->limit(50)
  	  ->orderBy("id desc")
      ->useQueryCache(true)->setQueryCacheLifeSpan(3600*24)  
  	  ->execute(array(), Doctrine::HYDRATE_ARRAY);
  }
}