<?php

/**
 * ShoutboxComsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShoutboxComsTable extends MsgMessagesTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShoutboxComsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShoutboxComs');
    }
}