<?php

/**
 * ShoutboxComs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zt2
 * @subpackage model
 * @author     Optix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShoutboxComs extends BaseShoutboxComs
{
  public function save(Doctrine_Connection $con = null) {
    // Saving comment
    $q = parent::save();

    // Notify author
    Doctrine::getTable('Notifications')->setNotification(
      "has commented your shout.",
      "comment_add.png",
      $this->getContent(),
      "shoutbox/show?id=".$this->Shoutbox->getId()
    )
    ->setOwner($this->Shoutbox->getAuthor())
    ->save();
	    
    return $q;
  }
}
