<?php

/**
 * TorrentsPeersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TorrentsPeersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TorrentsPeersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TorrentsPeers');
    }
}