<?php

/**
 * TorrentsPeersOffsetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TorrentsPeersOffsetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TorrentsPeersOffsetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TorrentsPeersOffset');
    }
}