<?php

/**
 * UploadsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UploadsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UploadsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Uploads');
    }

    public function getUploadsByUser($uid) {
      return Doctrine_Query::create()
      	->select('c.slug, u.title, u.slug, u.description')
      	->from('Uploads u')
        ->leftJoin('u.Categories c')
      	->where('u.author = ?', $uid)
      	->orderBy('u.id desc')
        ->useQueryCache(true)->setQueryCacheLifeSpan(3600*24)
        ->limit(100)
      	->execute();
    }
}