<?php

/**
 * UploadsHitsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UploadsHitsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UploadsHitsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UploadsHits');
    }
}